# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
# Use libvirt as the default provider
Vagrant.configure("2") do |config|
    config.vm.define :test_vm0 do |test_vm0|
        #test_vm0.vm.box = "segment-routing/ubuntu-16.04"
        test_vm0.vm.box = "generic/ubuntu1804"
        test_vm0.vm.hostname = "myhost.local"
        test_vm0.vm.network :public_network,
            :dev => "br0",
            :mode => "bridge",
            :type => "bridge"
        test_vm0.vm.synced_folder "/home/dutsai/ws-dutsai", "/home/vagrant/ws-dutsai"
    end
    config.vm.provider "libvirt" do |virt|
        virt.memory = 16384
        virt.cpus = 8
        virt.nested = true
        virt.cpu_mode = "host-model"
        virt.storage :file, :size => '30G', :type => 'qcow2'
        # Host use virbr1 to access the guest mgmt port (eth0)
        virt.management_network_device = 'virtbr1'
    end
end
